changelog:
  categories:
    - title: 🚀 Features
      labels:
        - enhancement
        - feature
    - title: 🚀 New Features
      labels:
        - feat
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 🧰 Maintenance
      labels:
        - chore
        - dependencies
        - documentation
  exclude:
    authors:
      - github-actions[bot]
